feat(update): Allow to use a bot account for the `update` action
Mergifyio/mergify pull request #4628
Opened 2022-05-01 14:34 UTC by ErwanSimonetti

The `update` action should be usable with a bot account

Fixes MRGFY-972

2022-05-02 11:36 UTC, Syffe commented on mergify_engine/branch_updater.py
> +async def update_with_api(ctxt: context.Context, github_user) -> None:
missing typing for `github_user` parameter

2022-05-02 12:58 UTC, Syffe commented on mergify_engine/tests/functional/actions/test_update.py
> +    async def test_update_action_with_bot(self):
```suggestion
    async def test_update_action_with_bot(self) -> None:
```

2022-05-09 09:16 UTC, sileht requested changes
I have the feeling that the zfixtures should only update TestUpdateAction* since you didn't touch other files.

2022-05-09 09:17 UTC, sileht commented on docs/source/actions/update.rst
> +It is possible to use this action with a bot.
You must add a rst table like other actions.

2022-05-09 09:17 UTC, sileht commented on releasenotes/notes/bot-user-update-action-6af260955bd77a61.yaml
> +    The ``update`` action is now usable with a bot
```suggestion
    The ``update`` action gets a new option ``bot_account``.

2022-07-04 07:23 UTC, Greesb requested changes

2022-07-04 07:23 UTC, Greesb commented on mergify_engine/actions/update.py
> +                ctxt, "action.rebase", {"bot_account": bool(self.config["bot_account"])}
Changing from `update` to `rebase` ? Aren't the `update` and `rebase` 2 different behaviors ?

2022-07-04 07:23 UTC, Greesb commented on mergify_engine/actions/update.py
> +                    f"Unable to comment: user `{bot_account}` is unknown. ",
Shouldn't it be
```suggestion
                    f"Unable to update: user `{bot_account}` is unknown. ",
```
?

2022-07-04 07:23 UTC, Greesb commented on mergify_engine/actions/update.py
> +                missing_feature_message="Rebase with `update_bot_account` set is unavailable",
```suggestion
                missing_feature_message="Update with `update_bot_account` set is unavailable",
```

2022-07-11 09:44 UTC, closed without merging